timaslj
johanhoffman/DD2363-VT20 pull request #19
Opened 2020-01-26 20:44 UTC by timaslj

Lab 2

2020-02-02 19:37 UTC, ajlace requested changes
I have requested 2 changes to lab 2. Other than those, it looks good.

2020-02-02 19:37 UTC, ajlace commented on Lab-2/timaslj_lab_2.ipynb
> +        "### **Blocked matrix-matrix product**"
I am assuming this is an error.

2020-02-02 19:37 UTC, ajlace commented on Lab-2/timaslj_lab_2.ipynb
> +        "      for i in range(size):\n",
Provide comments to clarify the tests.

2020-02-04 22:52 UTC, timaslj commented on Lab-2/timaslj_lab_2.ipynb
> +        "      for i in range(size):\n",
Added!

2020-02-04 22:52 UTC, timaslj commented on Lab-2/timaslj_lab_2.ipynb
> +        "### **Blocked matrix-matrix product**"
Added!

2020-02-12 19:19 UTC, ajlace approved these changes
I approve of the changes, however it seems as the updated file is outside the Lab2-folder (it does not affect anything really)

2020-02-12 20:20 UTC, merged