Kalmroth lab4
johanhoffman/DD2363-VT20 pull request #25
Opened 2020-02-08 17:16 UTC by krille71

2020-02-18 14:37 UTC, ajlace requested changes
Lab 4: Consider adding a more elaborate discussion of the results/lab in the future. Other than the changes requested, good job.

2020-02-18 14:37 UTC, ajlace commented on Lab-4/kalmroth_lab4.ipynb
> +        "# **Methods**"
Add either an explanation to how you got the different values for A and b, or include a reference to where these were found.

2020-02-18 14:37 UTC, ajlace commented on Lab-4/kalmroth_lab4.ipynb
> +        "# **Results**"
Add a plot showing exact solution vs your approximation.

2020-02-23 12:35 UTC, krille71 commented
Should be fixed now @ajlace

2020-02-25 16:07 UTC, ajlace approved these changes

2020-02-25 16:45 UTC, merged