Created using Colaboratory
johanhoffman/DD2363-VT20 pull request #27
Opened 2020-02-10 22:36 UTC by timaslj

2020-02-18 14:47 UTC, ajlace requested changes
The lab looks great. Only thing missing is a plot comparing the exact solution to the approximation.

2020-03-09 12:20 UTC, timaslj commented
Plot added!

2020-03-10 11:49 UTC, ajlace commented
Great. This lab is done! 🙂

2020-03-10 13:24 UTC, ajlace approved these changes

2020-03-10 13:57 UTC, ajlace approved these changes

2020-03-12 10:07 UTC, merged